[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false